
uiVariant.getValue = EEex_Menu_GetItemVariant
uiVariant.setValue = EEex_Menu_SetItemVariant

CGameObject.isSprite = EEex_GameObject_IsSprite
CGameObject.getClass = EEex_GameObject_GetClass
CGameObject.applyEffect = EEex_GameObject_ApplyEffect

CGameSprite.getActiveStats = EEex_Sprite_GetActiveStats
CGameSprite.getModalTimer = EEex_Sprite_GetModalTimer
CGameSprite.getModalState = EEex_Sprite_GetModalState
CGameSprite.getContingencyTimer = EEex_Sprite_GetContingencyTimer
CGameSprite.getCastTimer = EEex_Sprite_GetCastTimer
CGameSprite.getModalTimerPercentage = EEex_Sprite_GetModalTimerPercentage
CGameSprite.getContingencyTimerPercentage = EEex_Sprite_GetContingencyTimerPercentage
CGameSprite.getCastTimerPercentage = EEex_Sprite_GetCastTimerPercentage

Spell_Header_st.getAbility = EEex_Resource_GetSpellAbility
Spell_Header_st.getAbilityForLevel = EEex_Resource_GetSpellAbilityForLevel
